version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: dramzy_db
      POSTGRES_USER: dramzy
      POSTGRES_PASSWORD: dramzy
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 todolistapi.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SECRET_KEY: 'generated-secret-key'
      DB_NAME: dramzy_db
      DB_USER: dramzy
      DB_PASSWORD: dramzy
      DB_HOST: db
      DB_PORT: 5432
