version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: dramzy_db
      POSTGRES_USER: dramzy
      POSTGRES_PASSWORD: dramzy
    ports:
      - "5432:5432"


  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: sh -c "python3 manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  data:
