apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todolist-app
  template:
    metadata:
      labels:
        app: todolist-app
    spec:
      containers:
      - name: todolist-app
        image: gcr.io/your-project-id/todolist-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          value: "your-generated-secret-key"
        - name: DB_NAME
          value: "dramzy_db"
        - name: DB_USER
          value: "dramzy"
        - name: DB_PASSWORD
          value: "dramzy"
        - name: DB_HOST
          value: "db"
        - name: DB_PORT
          value: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: todolist-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: todolist-app
